#include<cstdio>
int main(){
	int n,a,b,c,d,e,f,g,h,i;
	bool p[15]={0};
	scanf("%d",&n);
	if(n==1)
	    printf("1");
	if(n==2)
		printf("1    2\n2    1");
	if(n==3){
		for(g=1;g<=3;g++){
	    	if(p[g]==0){
	    		p[g]=1;
	    		for(h=1;h<=3;h++){
	    			if(p[h]==0){
	    			    p[h]=1;
	    			    for(i=1;i<=3;i++){
	    			        if(p[i]==0){
	    			            printf("    %d    %d    %d\n",g,h,i);
	    			            break;
	    			        }
	    			  	}
	    			    p[h]=0;
	                }
	    	    }
	    	    p[g]=0;
	        }
	    }
	}
	if(n==4){
		for(f=1;f<=4;f++){
	    	if(p[f]==0){
	    		p[f]=1;
	    		for(g=1;g<=4;g++){
	    			if(p[g]==0){
	    			    p[g]=1;
	    			    for(h=1;h<=4;h++){
	    			    if(p[h]==0){
	    			        p[h]=1;
	    			        for(i=1;i<=4;i++){
	    			            if(p[i]==0){
	    			                printf("    %d    %d    %d    %d\n",f,g,h,i);
	    			                break;
	    			            }
	    			        }
	    			        p[h]=0;
	    			    }
	    			}
	    		        p[g]=0;
	    		    }
	    	    }
	    	    p[f]=0;
	    	}
	    }
	}
	if(n==5){
		for(e=1;e<=5;e++){
	    	if(p[e]==0){
	    		p[e]=1;
	    		for(f=1;f<=5;f++){
	    			if(p[f]==0){
	    			    p[f]=1;
	    			    for(g=1;g<=5;g++){
	    			        if(p[g]==0){
	    			            p[g]=1;
	    			            for(h=1;h<=5;h++){
	    			                if(p[h]==0){
	    			                	p[h]=1;
	    			                	for(i=1;i<=5;i++){
	    			                		if(p[i]==0){
	    			                			printf("    %d    %d    %d    %d    %d\n",e,f,g,h,i);
	    			                			break;
	    			                		}
	    			                	}
	    			                p[h]=0;
	    			                }
	    			            }
	    			            p[g]=0;
	    			        }
	    			    }
	    			    p[f]=0;
	    			}
	    		}
	    		p[e]=0;
	    	}
	    }
	}
	if(n==6){
		for(d=1;d<=6;d++){
	    	if(p[d]==0){
	    		p[d]=1; 
	            for(e=1;e<=6;e++){
	    		    if(p[e]==0){
	    	    		p[e]=1;
	    			    for(f=1;f<=6;f++){
	    			        if(p[f]==0){
	    			            p[f]=1;
	    			            for(g=1;g<=6;g++){
	    			                if(p[g]==0){
	    			                    p[g]=1;
	    			                    for(h=1;h<=6;h++){
	    			                    	if(p[h]==0){
	    			                    		p[h]=1;
	    			                    		for(i=1;i<=6;i++){
	    			                		    	if(p[i]==0){
	    			                			        printf("    %d    %d    %d    %d    %d    %d\n",d,e,f,g,h,i);
	    			                			        break;
	    			                		    	}
	    			                	    	}
	    			                	    	p[h]=0;
	    			                	    }
	    			                    }
	    			                    p[g]=0;
	    			                }
	    			            }
	    			            p[f]=0;
	    			        }
	    			    }
	    		    	p[e]=0;
	    		    }
	    	    }
	    	    p[d]=0;
	        }
	    }
	}
	if(n==7){
		for(c=1;c<=7;c++){
	    	if(p[c]==0){
	    		p[c]=1;
	    		for(d=1;d<=7;d++){
	    			if(p[d]==0){
	    			    p[d]=1; 
	    			    for(e=1;e<=7;e++){
	    			        if(p[e]==0){
	    			            p[e]=1;
	    			            for(f=1;f<=7;f++){
	    			                if(p[f]==0){
	    			                	p[f]=1;
	    			                	for(g=1;g<=7;g++){
	    			                		if(p[g]==0){
	    			                			p[g]=1;
	    			                			for(h=1;h<=7;h++){
	    			                			    if(p[h]==0){
	    			                			    	p[h]=1;
	    			                			    	for(i=1;i<=7;i++){
	    			                			    		if(p[i]==0){
	    			                			    			printf("    %d    %d    %d    %d    %d    %d    %d\n",c,d,e,f,g,h,i);
	    			                			    		    break;
	    			                			    		}
	    			                			    	}
	    			                					p[h]=0;
	    			                			   	}
	    			                			}
	    			                			p[g]=0;
	    			                		}
	    			                	}
	    			                    p[f]=0;
	    			                }
	    			            }
	    			            p[e]=0;
	    			       	}
	    			    }
	    			    p[d]=0;
	    			}
	    		}
	    		p[c]=0;
	    	}
	    }
	}
	if(n==8){
		for(b=1;b<=8;b++){
	    	if(p[b]==0){
	    		p[b]=1;
	    		for(c=1;c<=8;c++){
	    			if(p[c]==0){
	    				p[c]=1;
	    				for(d=1;d<=8;d++){
	    					if(p[d]==0){
	    			            p[d]=1; 
	    			            for(e=1;e<=8;e++){
	    			                if(p[e]==0){
	    			                	p[e]=1;
	    			                	for(f=1;f<=8;f++){
	    			                		if(p[f]==0){
	    			                			p[f]=1;
	    			                			for(g=1;g<=8;g++){
	    			                			    if(p[g]==0){
	    			                			    	p[g]=1;
	    			                			    	for(h=1;h<=8;h++){
	    			                			    		if(p[h]==0){
	    			                			    			p[h]=1;
	    			                			    			for(i=1;i<=8;i++){
	    			                			    				if(p[i]==0){
	    			                			    					printf("    %d    %d    %d    %d    %d    %d    %d    %d\n",b,c,d,e,f,g,h,i);
	    			                			    				    break;
	    			                			    				}
	    			                			    			}
	    			                			   				p[h]=0;
	    			                			   			}
	    			                			   		}
	    			                			   		p[g]=0;
	    			                		    	}
	    			               			    }
	    			               			    p[f]=0;
	    			               			}
	    			               		}
	    			               		p[e]=0;
	    			               	}
	    			            }
	    			            p[d]=0;
	    			        }
	    				}
	    				p[c]=0;
	    			}
	    		}
	    		p[b]=0;
	    	}
	    }
	}
	if(n==9){
	    for(a=1;a<=9;a++){
	    	p[a]=1;
	    	for(b=1;b<=9;b++){
	    		if(p[b]==0){
	    			p[b]=1;
	    			for(c=1;c<=9;c++){
	    				if(p[c]==0){
	    					p[c]=1;
	    					for(d=1;d<=9;d++){
	    						if(p[d]==0){
	    			                p[d]=1; 
	    			                for(e=1;e<=9;e++){
	    			                	if(p[e]==0){
	    			                		p[e]=1;
	    			                		for(f=1;f<=9;f++){
	    			                			if(p[f]==0){
	    			                			    p[f]=1;
	    			                			    for(g=1;g<=9;g++){
	    			                			    	if(p[g]==0){
	    			                			    		p[g]=1;
	    			                			    		for(h=1;h<=9;h++){
	    			                			    			if(p[h]==0){
	    			                			    				p[h]=1;
	    			                			    				for(i=1;i<=9;i++){
	    			                			    					if(p[i]==0){
	    			                			    						printf("    %d    %d    %d    %d    %d    %d    %d    %d    %d\n",a,b,c,d,e,f,g,h,i);
	    			                			    					    break;
	    			                			    					}
	    			                			    				}
	    			                			    				p[h]=0;
	    			                			    			}
	    			                			    		}
	    			                			    		p[g]=0;
	    			                			    	}
	    			                			    }
	    			                			    p[f]=0;
	    			                			}
	    			                		}
	    			                		p[e]=0;
	    			                	}
	    			                }
	    			                p[d]=0;
	    			            }
	    					}
	    					p[c]=0;
	    				}
	    			}
	    			p[b]=0;
	    		}
	    	}
	    	p[a]=0;
	    }
	}
	return 0;
}

